# name of the workflow
name: Check dbt Cloud Job Run Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab if needed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "retrieve_dbt_cloud_job_status"
  retrieve_dbt_cloud_job_run_status:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # running the step to get the most recent job run results and return the status
      - name: Get dbt Cloud job run and return the status
        id: get_job_run
        uses: stevedow99/dbt-cloud-get-job-run-action@V1.0
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
          dbt_cloud_account_id: 96504
          dbt_cloud_job_id: 130247

      # if the job run was a success we comment on the PR with a check and a link to the dbt Cloud Job run
      - name: PR comment with sucess
        uses: mshick/add-pr-comment@v1
        if:  steps.selftest.outputs.dbt_cloud_job_run_status == 'Success'
        with:
          message: |
            ## ✅ dbt Cloud job finished with the status ${{ steps.get_job_run.outputs.dbt_cloud_job_run_status }}
            View the dbt Cloud job run [here](${{ steps.get_job_run.outputs.dbt_cloud_job_run_url }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false # This is the default
          
          
      # if the run was a failure we comment on the PR with a X and a link to the dbt Cloud Job run
      - name: PR comment with failure
        uses: mshick/add-pr-comment@v1
        if:  steps.selftest.outputs.dbt_cloud_job_run_status != 'Success'
        with:
          message: |
            ## ❌ dbt Cloud job finished with the status ${{ steps.get_job_run.outputs.dbt_cloud_job_run_status }}
            View the dbt Cloud job run [here](${{ steps.get_job_run.outputs.dbt_cloud_job_run_url }}")
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false # This is the default

      # using the returned run status to throw an error on the PR if the dbt cloud job was not a sucess
      - name: Check on dbt cloud job failures
        if:  steps.get_job_run.outputs.dbt_cloud_job_run_status != 'Success'
        run: |
          echo "dbt cloud job failed or was cancelled, run status: ${{ steps.get_job_run.outputs.dbt_cloud_job_run_status }}"
          echo "view dbt cloud job run here: ${{ steps.get_job_run.outputs.dbt_cloud_job_run_url }}"
          exit 1

        # if the job was a success we log it
      - name: Check on dbt cloud job success
        if:  steps.get_job_run.outputs.dbt_cloud_job_run_status == 'Success'
        run: |
          echo "dbt cloud finished sucessfully, run status: ${{ steps.get_job_run.outputs.dbt_cloud_job_run_status }}"
          echo "view dbt cloud job run here: ${{ steps.get_job_run.outputs.dbt_cloud_job_run_url }}"
          exit 0
