# This is a basic workflow to help you get started with Actions

name: Check dbt Cloud Job Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  retrieve_dbt_cloud_job_status:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Self test
        id: selftest
        uses: stevedow99/sample-python-action@main
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
          dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
          dbt_cloud_job_id: 130247
      - name: temp test
        run: echo "${{ steps.selftest.outputs.dbtcloudjobstatus }}""
      - name: Check on dbt cloud job failures
        if:  steps.selftest.outputs.dbtcloudjobstatus != 'Success'
        run: |
          echo "dbt cloud job failed or was cancelled"
          exit 1
      - name: Check on dbt cloud job sucess
        if:  steps.selftest.outputs.dbtcloudjobstatus == 'Success'
        run: |
          echo "dbt cloud job was sucessful"
          exit 0
