# This is a basic workflow to help you get started with Actions

name: Check dbt Cloud Job Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  retrieve_dbt_cloud_job_status:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Get dbt cloud run id
      - uses: catchco/dbt-cloud-get-run-id@latest
        id: dbt_cloud_get_run_id
        with:
            dbt_cloud_account_id: 96504
            dbt_cloud_api_key: ${{ secrets.NON_PII_API_KEY }}
            dbt_cloud_job_id: 130247
            dbt_cloud_request_limit: 1000
      - name: Show Response
        run: |
          echo ${{ steps.dbt_cloud_get_run_id.outputs }}