# This is a basic workflow to help you get started with Actions

name: Check dbt Cloud Job Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  retrieve_dbt_cloud_job_status:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Self test
        id: selftest
        uses: stevedow99/sample-python-action@main
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
          dbt_cloud_account_id: 96504
          dbt_cloud_job_id: 130247
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            dbt Cloud job finished with the status **${{ steps.selftest.outputs.dbt_cloud_job_run_status }}**
            View the dbt Cloud job run [here](${{ steps.selftest.outputs.dbt_cloud_job_run_url }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false # This is the default
      - name: Check on dbt cloud job failures
        if:  steps.selftest.outputs.dbt_cloud_job_run_status != 'Success'
        run: |
          echo "dbt cloud job failed or was cancelled, run status: ${{ steps.selftest.outputs.dbt_cloud_job_run_status }}"
          echo "view dbt cloud job run here: ${{ steps.selftest.outputs.dbt_cloud_job_run_url }}"
          exit 1
      - name: Check on dbt cloud job success
        if:  steps.selftest.outputs.dbt_cloud_job_run_status == 'Success'
        run: |
          echo "dbt cloud finished sucessfully, run status: ${{ steps.selftest.outputs.dbt_cloud_job_run_status }}"
          echo "view dbt cloud job run here: ${{ steps.selftest.outputs.dbt_cloud_job_run_url }}"
          exit 0
