# This is a basic workflow to help you get started with Actions

name: Check dbt Cloud Job Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  retrieve_dbt_cloud_job_status:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Get dbt Cloud Job Status
       id: get_dbt_cloud_run
       uses: fjogeleit/http-request-action@v1
       with:
        url: 'https://cloud.getdbt.com/api/v2/accounts/96504/runs/?job_definition_id=130247'
        method: 'GET'
        customHeaders: '{"Authorization": "${{ secrets.NON_PII_API_KEY }}"}'
        run: |
          echo ${{ steps.get_dbt_cloud_run.outputs.response }}
