# This is a basic workflow to help you get started with Actions

name: run check

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test_with_details:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: .github/workflows/check_dbt_job_and_return_details.yml
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test With Details
        conclusion: success
        action_url: https://example.com/action
        details_url: https://example.com/details
